server:
  port: 8890

spring.mvc.view:
  prefix: /WEB-INF/views/
  suffix: .jsp

#mybatis
#mybatis-plus:
mybatis-plus:
  mapper-locations: classpath:/static/mapping/*.xml
  typeAliasesPackage: com.sf.game.entity #实体扫描，多个package用逗号或者分号分隔
#  typeEnumsPackage: com.sf.game.enums
  configuration:
      map-underscore-to-camel-case: false
      cache-enabled: false
  global-config:
    id-type: 0 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 2 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-column-underline: true #驼峰下划线转换
    refresh-mapper: true #刷新mapper 调试神器
    capital-mode: false #数据库大写下划线转换
    logic-delete-value: 0 #逻辑删除配置
    logic-not-delete-value: 1 #逻辑删除配置
#    meta-object-handler: com.baomidou.springboot.xxx #自定义填充策略接口实现
#    sql-injector: com.baomidou.springboot.xxx #自定义SQL注入器
#    key-generator: com.baomidou.springboot.xxx #序列接口实现类配置


spring.datasource:
    url: jdbc:mysql://localhost:3306/game
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: a123456